# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build aws_cli_s3 linux

run-name: build Version linux ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v3
      name: checkout project

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build linux
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: go build -v -o bin/aws_cli

    - name: Create Artifact-linux
      if: ${{ matrix.os }} == "ubuntu-latest"
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact-linux-${{ github.ref_name }}
        path: ./bin/aws_cli
    
    - name: Build windows
      if: ${{ matrix.os }} == "windows-latest"
      run: go build -v -o bin/aws_cli.exe

    - name: Create Artifact-windows
      if: ${{ matrix.os }} == "windows-latest"
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact-windows-${{ github.ref_name }}
        path: ./bin/aws_cli.exe
