name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release_create:
    name: Release Create
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/create-release@v1
        name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: verifique o executável no pipeline de deploy.
          draft: false
          prerelease: false